### ISSUE TITLE
Cannot use -var with nested variables

### ISSUE THREAD

**Issue by mwalters-workmarket** [hashicorp/levant#257]
given a levant file:
```
{
  nested:
    test:  true

  flat_test: true
}
```

and a nomad file containing
```
template {
  data = <<EOH
nested value = [[ .nested.test ]]
flat value = [[.flat_test]]
  
EOH

  destination = "secrets/file.env"
  env = true
 }
```
when I execute `levant render -var "flat_test=false" -var "nested.test=false" -var-file=myconfig.yaml mynomad.nomad`

the output includes
```
nested value = true
flat value = false
```

I would expect
```
nested value = false
flat value = false
```

Is it possible to override nested values ?

**Comment by jrasell** [comment]
@mwalters-workmarket this is a problem is the current implementation of the FlagVars. I'll look into fixing this up.

**Comment by EvanErcolano** [comment]
@jrasell I see how we could change the implementation of FlagVars to support this functionality. Did you already start the work on this or may I take a swing at it?

**Comment by jrasell** [comment]
@EvanErcolano please feel free to take a swing if you have the time, that would be greatly appreciated.
