### ISSUE TITLE
Distributing levant as a Debian package for Dokku

### ISSUE THREAD

**Issue by josegonzalez** [hashicorp/levant#281]
**Description**

I'm using this project within [dokku-scheduler-nomad](https://github.com/dokku/dokku-scheduler-nomad) to provide integration with Nomad for the Dokku project. I would like to be able to package levant as a debian package if possible, and place it within the official Dokku package cloud repository. Is this fine with you?

**Comment by jrasell** [comment]
@josegonzalez this is more than fine with me. Is this something you are able to look at?

**Comment by jrasell** [comment]
Closing as the question was answered.
