### ISSUE TITLE
Show how to loop over an array

### ISSUE THREAD

**Issue by spuder** [hashicorp/levant#294]
Thanks for making this awesome tool. There aren't any documentation examples that show how to loop over an array. For example:

```
job "foo" {
  region = "foo"
  datacenters = [[.datacenters]]
}
```
In my variable file
```
---
datacenters:   
  - A
  - B
```

Levant does not quote or comma separate the list, so it outputs

```
datacenters = [ A B ]
```
Instead of 
```
datacenters = [ "A", "B" ]
```

How can I quote and comma separate the array?

**Comment by AdrienFromToulouse** [comment]
👋indeed that's a great tool!

I am also a bit confused on my end in regard to `list`.

Let's say you have a list of DCs defined in an environment variable, let's say `DCs = ["dc1", "dc2"].
How would it be reflected in a `.tf` like template format?
I was expecting something like:

```terraform
datacenters = [[  env "DCs" ]]
```
But does not ends up well it seems or I might be doing something wrong.

I had a look in the test cases but could not find one involving `list`.

I would be grateful for some guidance .

**Comment by AdrienFromToulouse** [comment]
👋indeed that's a great tool!

I am also a bit confused on my end in regard to list.

Let's say you have a list of DCs defined in an environment variable, let's say:

```terraform
variable "datacenters" {
  type        = "list"
  default     = [ "dc1", "dc2" ]
}
```

```terraform
# in levant job template
datacenters = [[ .datacenters ]]
```

It does not succeed:

```console
[ERROR] levant/command: error parsing: At 2:18: unexpected token while parsing list: IDENT
```

I had a look in the test cases but could not find one involving list.

I would be grateful for some guidance .

Cheers!

**Comment by Mongey** [comment]
```
    datacenters =  [ [[range $index, $value := .datacenters]][[if ne $index 0]],[[end]]"[[$value]]"[[end]] ]
```
produces
```
    datacenters = [ "1","2","3" ]
```

**Comment by arjunkchr** [comment]
Along the similar lines, is there a way to iterate over a directory, read each file in that directory using **fileContents** and then write out each content using **destination** attribute in nomad?

**Comment by jrasell** [comment]
Closing as the original question has been answered.
