### ISSUE TITLE
Add merge maps function to render template

### ISSUE THREAD

**Issue by DNAlchemist** [hashicorp/levant#306]
As implemented in terraform.
It's needed to merge map variables.
https://github.com/hashicorp/terraform/blob/master/lang/functions.go#L88
https://github.com/hashicorp/terraform/blob/master/lang/funcs/collection.go#L873

**Comment by jrasell** [comment]
This should now be resolved by the addition of Sprig template funcs which include the `merge` and `mustMerge` dict funcs.
