### ISSUE TITLE
Host volumes are not supported

### ISSUE THREAD

**Issue by tylermenezes** [hashicorp/levant#323]
**Description**

Levant does not currently support the [`volume`](https://www.nomadproject.io/docs/job-specification/volume.html) or [`volume_mount`](https://www.nomadproject.io/docs/job-specification/volume_mount.html) stanzas necessary for host volumes.

**Relevant Nomad job specification file**

```
job "test" {
  region = "global"
  datacenters = ["srnd"]
  type = "service"

  group "test" {

    volume "test" {
      type      = "host"
      read_only = false
      source    = "test"
    }

    count = 1
    task "test" {
      driver = "docker"
      config {
        image = "hello-world"
      }

      volume_mount {
        volume      = "test"
        destination = "/test"
        read_only   = false
      }
    }
  }
}
```

**Output of `levant version`:**

```
Levant v0.2.9
Date: 2019-12-27T09:43:30Z
Commit: 0f1913ea3d77584ddd0696da429dcf05572a73a0
Branch: 0.2.9
State: 0.2.9
Summary: 0f1913ea3d77584ddd0696da429dcf05572a73a0
```

**Output of `consul version`:**

```
Consul v1.6.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Output of `nomad version`:**

```
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)
```

**Debug log outputs from Levant:**

```
$ levant plan test.nomad                                                                                                                                                                          1 master?
[ERROR] levant/command: error parsing 'job': 1 error occurred:
	* group: 'test' -> invalid key: volume
```

... and if I comment that stanza out...

```
$ levant plan test.nomad                                                                                                                                                                            master?
[ERROR] levant/command: error parsing 'job': 1 error occurred:
	* group: 'test', task: 'test' -> invalid key: volume_mount
```

... nomad works fine with the same file...

```
$ nomad plan test.nomad                                                                                                                                                                             master?
+ Job: "test"
+ Task Group: "test" (1 create)
  + Task: "test" (forces create)
```

**Comment by tylermenezes** [comment]
(I'm not really sure where the config validation is taking place, but if you can point me in the right direction I'm happy to try to do a PR for this, although I'm not much of a Go dev.)

**Comment by joshuaclausen** [comment]
@tylermenezes 
There are 2 pull requests that fix this issue, so if you sync to one of those specific pull requests (or their parent repos), you should have a functional levant binary that supports the new jobspec keys:
- https://github.com/jrasell/levant/pull/327
- https://github.com/jrasell/levant/pull/328


Then, you can build levant for your platform by doing the following:
- install go (latest version)
- make sure your gopath environment variable is set
- go get github.com/jrasell/levant
- look in either of the following for the built binary (levant, or levant.exe):
 - $gopath/go/bin/
 - $gopath/go/src/github.com/jrasell/levant/
- in the root of the repo you synced, run "GOOS=windows go build" to build for windows (as an example)... or just "go build" to build for your current OS
