### ISSUE TITLE
Consul Connect not yet supported?

### ISSUE THREAD

**Issue by ssagraloff** [hashicorp/levant#324]
**Description**

We just switched our live system to 3 cloud datacenteres a few months ago and using consul connect for our services. Now we want to switch our deployment to nomad + consul connect.

But it seams like levant is not able to interpret the consul connect syntax which was introduced with nomad 10.0.
I just created 2 simple nomad plans to simulate consul connect like it is described in HashiCorp's guide: https://www.nomadproject.io/guides/integrations/consul-connect/index.html

Both jobs are working well with nomad. I pasted just one of it because the output of levant is the same for both. See debug output of levant at the bottom.

**Relevant Nomad job specification file**

```
job "gitea-client" {
  datacenters = ["nomad2"]
  type = "service"

  update {
    max_parallel = 1
    progress_deadline = "0"
    auto_revert = false
    canary = 0
  }

  group "integration" {
    count = 1
    
    restart {
      attempts = 1 
      interval = "1m"
      delay = "15s"
      mode = "fail"
    }

    network {
      mode = "bridge"
      port "http" { 
        static = "9002"
        to     = "9002"
        }
    }

    service {
      name = "gitea-client"
      tags = ["tcp"]
      port = "http"
      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "gitea"
              local_bind_port  = 4711 
            }
          }
        }
      }
    }

    task "gitea" {
      driver = "exec"
      
      artifact {
        source = "https://github.com/go-gitea/gitea/releases/download/v1.9.4/gitea-1.9.4-linux-amd64"
      }

      config {
        command = "./local/gitea-1.9.4-linux-amd64"
        args = [ "web", "-port", "9002" ]
      }

      env {
        GITEA_URL = "http://${NOMAD_UPSTREAM_ADDR_gitea}"
      }

      resources {
        cpu    = 500 # 500 MHz
        memory = 1024 
        network {
          mbits = 100
        }
      }
    }
  }
}
```

**Output of `levant version`:**

```
Levant v0.2.9
Date: 2019-12-27T09:43:30Z
Commit: 0f1913ea3d77584ddd0696da429dcf05572a73a0
Branch: 0.2.9
State: 0.2.9
Summary: 0f1913ea3d77584ddd0696da429dcf05572a73a0
```

**Output of `consul version`:**

```
Consul v1.6.2
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

**Output of `nomad version`:**

```
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)
```

**Additional environment details:**
```
Linux nomadtest-1 4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
```
**Debug log outputs from Levant:**
```
2020-01-21T17:24:23+01:00 |DEBU| template/render: no variable file passed, trying defaults
2020-01-21T17:24:23+01:00 |DEBU| helper/files: no default var-file found
2020-01-21T17:24:23+01:00 |DEBU| template/render: no command line variables passed
[ERROR] levant/command: error parsing 'job': 2 errors occurred:
	* group: 'integration' -> invalid key: network
	* group: 'integration' -> invalid key: service
```

**Comment by lsc** [comment]
It looks like the issue is that the version of Nomad imported by levant is at version 0.9.6 right now, and that doesn't support the consul connect features.
 
I tried to upgrade the dependency to nomad@v0.10.4 and nomad/api to the corresponding commit hash  (api v0.0.0-20200201010253-0040c75e8e7c) and that seems to fix the immediate problem.

As I am running a mac, I had to adapt the job specification a bit for it to even try to place the job. 

I will open a PR with the changes and let's see what @jrasell says.

**Comment by pznamensky** [comment]
@jrasell could you please take a look?

**Comment by vjeantet** [comment]
Hello, any update on this usecase ?

**Comment by guaychou** [comment]
hello any update ?

**Comment by redfive** [comment]
Could use this Nomad upgrade to get access to host volumes as well. Also, 0.11.3 is out so we could just make the jump all the way to that...

**Comment by lsc** [comment]
> Could use this Nomad upgrade to get access to host volumes as well. Also, 0.11.3 is out so we could just make the jump all the way to that...

You can probably do what I did in my original PR but bump the version even higher and just build it locally. 
We don't really use the consul connect or host volume features in our Nomad deployment so we haven't bothered building it ourselves.

**Comment by redfive** [comment]
@lsc Not that familiar updating vendored packages in go projects. How would I go about updating that? I am building levant into a container which is doing a `make build` as part of the container build already so probably this would be simple. Thanks in advance.
