### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by daniils-hq** [hashicorp/levant#337]
With the last release in December 2019 and 10 pending PR's, is this project supported by the repo owner?

**Comment by jrasell** [comment]
I need to find time to address the outstanding PR's and plan the next set of work. The past 6 months have been very busy and I have not been able to spend time on this project but I am hoping to sort this soon.

**Comment by daniils-hq** [comment]
With the latest stable version of Nomad being 0.11 (and 0.12 upcoming), without https://github.com/jrasell/levant/pull/327 merged this amazing software is not usable. It is very sad we or other people who stay with the latest Nomad version could not use Levant.

**Comment by jrasell** [comment]
The project has now been moved into the HashiCorp repository which allows me to work on this during my normal working day, dependant on priorities and workload.
