### ISSUE TITLE
Access global variable at inside loop

### ISSUE THREAD

**Issue by liemle3893** [hashicorp/levant#357]
**Description**
Cannot access variable inside a loop.

**Relevant Nomad job specification file**

```
# example.nomadtpl
[[ range $i := loop ( .count | parseInt) ]]
[[ .global_value ]]-[[$i]]
[[end]]
```

```yaml
# config.yaml
count: "3"
global_value: "text"
```

```shell
$ levant render -var-file=config.yaml -out=example.nomad example.nomadtpl
```

**Result**: __[ERROR] levant/command: template: jobTemplate:2:3: executing "jobTemplate" at <.global_value>: can't evaluate field global_value in type int64__

**Expected output**:
```hcl
# example.nomad
text-0
text-1
text-2
```

**Output of `levant version`:**

```
v0.3.0-dev
```

**Comment by pmcatominey** [comment]
Hey @liemle3893,

You can use `$.` to access the parent scope:

```
# example.nomadtpl
[[ range $i := loop ( .count | parseInt) ]]
[[ $.global_value ]]-[[$i]]
[[end]]
```

**Comment by liemle3893** [comment]
@pmcatominey Thank you, that neat. Hope to add that into document.
Going to close this issue. Thank again.
