### ISSUE TITLE
Job parsing error with Nomad 0.12.X

### ISSUE THREAD

**Issue by stevenscg** [hashicorp/levant#364]
**Description**

While upgrading for Nomad 0.12 compatibility per the published upgrade guide, the `network` and `service` stanzas were moved from the `task` level to the `group` level. When rendering the job and submitting it to the Nomad cluster, the following new errors were returned as shown below. This appears to be an issue blocking us from adopting the latest job file recommendations for 0.12 and beyond.

```
2020-10-05T18:07:35Z |INFO| helper/variable: using command line variable with key version and value f5bb795
2020-10-05T18:07:35Z |INFO| helper/variable: using variable with key region and value us from file
2020-10-05T18:07:35Z |INFO| helper/variable: using variable with key datacenter and value us1 from file
....
[ERROR] levant/command: error parsing 'job': 2 errors occurred:
* group: 'api' -> invalid key: network
* group: 'api' -> invalid key: service
```

**Relevant Nomad job specification file**

```
job "api" {
    type = "service"

    region = "us"
    datacenters = ["us1"]

    group "api" {
        count  = 1

        network {
            port "fpm" {}
        }

        service {
            name = "api"
            port = "fpm"
        }

        task "api-php-fpm" {
            driver = "docker"

            ....
        }
    }
}
```

**Output of `levant version`:**

```
Levant v0.2.9
Date: 2019-12-27T09:43:30Z
Commit: 0f1913ea3d77584ddd0696da429dcf05572a73a0
Branch: 0.2.9
State: 0.2.9
Summary: 0f1913ea3d77584ddd0696da429dcf05572a73a0
```

**Output of `nomad version`:**

```
Nomad v0.12.5 (514b0d667b57068badb43795103fb7dd3a9fbea7)
```

**Comment by stevenscg** [comment]
@jrasell Is this likely a dupe of or fixed by https://github.com/hashicorp/levant/pull/358?

**Comment by cgbaker** [comment]
correct. i verified that this spec parses correctly with ca9da42491f6ebec935f5dd74679621671c27438

look for this support (and Nomad 1.0.0) in a release in the next few days
