### ISSUE TITLE
parseTFVars supports only strings

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/levant#378]
**Description**

I'm not able to use the "type" / "description" keywords in the definition of a variable.   
It stopped working at commit be00465ca643af991d88f69b44608cdbc7353a1d with the introduction of 
```
type terraformVar struct {
	Key     string `hcl:"key,label"`
	Default string `hcl:"default"`
}
```
Which limits the type of a variable to string: i.e. lists aren't supported anymore and the "description" field isn't either.  
Any particular reason why the support for lists was dropped @jrasell ?

Using the following example Nomad job / var file:   
```
variable "resources_cpu_string" {
  description = "the CPU in MHz to allocate to the task group"
  type        = "string"
  default     = 250
}

variable "resources_cpu_list" {
  type        = "list"
  default     = [1,2,3]
}
```
And a random non-valid Nomad job:
```
job "ingress-example" {

  datacenters = ["dc1"]

  group "ingress-group" {

    network {
      mode = "bridge"
    }
  }
}
```
Throws:
```
./bin/levant render -var-file=test.tf gateway.nomad    
[ERROR] levant/command: test.tf:2,3-14: Unsupported argument; An argument named "description" is not expected here., and 3 other diagnostic(s)
```

**Output of `levant version`:**
```
0.3.0-beta1
```

**Comment by jrasell** [comment]
Closed by #380
