### ISSUE TITLE
official docker image doesn't exist

### ISSUE THREAD

**Issue by Freax13** [hashicorp/levant#389]
The README.md says that there should be a docker image of levant:
> A docker image can be found on Docker Hub, the latest version can be downloaded using docker pull hashicorp/levant.

However that image doesn't exist. There's an image from before the repo changed owners under jrasell/levant, but that image hasn't been updated in a year

**Comment by cgbaker** [comment]
Hi @Freax13 , I see the image for the latest release in Docker Hub: 
https://hub.docker.com/r/hashicorp/levant/tags

And as you, images from previous releases are available under `jrasell/levant`.

**Comment by Freax13** [comment]
Ah okay. I was assuming there was a image tagged "latest", but since it's the next version is still in beta, it makes sense that there isn't a image tagged "latest" yet
