### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/levant#396]
The last stable release is more than a year old. Is there any plan to cut a new release?

**Comment by jrasell** [comment]
Hi @fredwangwang, yes there is a plan to do this within the upcoming week!

**Comment by fredwangwang** [comment]
Awesome! Looking forward to it, thanks for the updated!

**Comment by rodzyn** [comment]
@jrasell Hi, do you have any updates on the release plans?

**Comment by jrasell** [comment]
@rodzyn inbound this week!

**Comment by tcurdt** [comment]
yay! :) binaries are still coming?

**Comment by cgbaker** [comment]
binaries are up at https://releases.hashicorp.com/levant/0.3.0/
