### ISSUE TITLE
Support for memory_max parameter

### ISSUE THREAD

**Issue by leanst-daniel** [hashicorp/levant#409]
**Support for memory_max parameter**

```
Levant doesn't support the memory_max parameter in the resource section of a Nomad task.
https://www.nomadproject.io/docs/job-specification/resources#memory_max
```

**Relevant Nomad job specification file**

```
resources {
  cpu        = 1000
  memory     = 150
  memory_max = 350
}
```

**Output of `levant version`:**

```
0.3.0
```

**Output of `nomad version`:**

```
1.1.0
```

**Additional environment details:**

**Debug log outputs from Levant:**
```
'levant deploy -force -var CI_PROJECT=${CI_PROJECT_TITLE} -var CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE} ./Hashistack/nomad/job/services.hcl
[ERROR] levant/command: error parsing 'job': 1 error occurred:
    * group: 'Refresh_Planning_Service', task: 'Refresh_Planning_Service', resources -> resources -> invalid key: memory_max
```

**Comment by jrasell** [comment]
Hi @leanst-daniel thanks for raising this issue. I'll work on updating the Nomad dependancy this week to allow this to work as expected.

**Comment by leanst-daniel** [comment]
Thank you @jrasell !
works :)

**Comment by rwojsznis** [comment]
Hey @jrasell thanks for fixing this, I can confirm as well that it works when build from source! <3

Any chance to release a `-dev` version of docker image as well? (forked a github action, realized I can use official levant image, realized version 0.3.0 still fails on config with `memory_max`)

**Comment by bbarman4u** [comment]
@jrasell I am little confused since the issue was closed, but was this fix ported to any of the latest releases ?
