### ISSUE TITLE
Question: why does levant plan exit 1 when no change is detected?

### ISSUE THREAD

**Issue by lhayhurst** [hashicorp/levant#417]
When you run `levant plan` (`v0.3.0`), it will exit 1 if no change is detected. 
```
$  levant plan -address=https://valid-nomad-url -log-level=info /tmp/jobfile.nomad    
2021-07-14T15:45:51-07:00 |INFO| levant/plan: no changes detected for job
2021-07-14T15:45:51-07:00 |INFO| levant/plan: no changes found in job
$ echo $?                                                    
1
```
Is this intentional? My understanding of exit code 1 in UNIX is that indicates a syntax error (for example, if you didn't provide enough or correct arguments to a cli; see [this SO article](https://stackoverflow.com/questions/20965762/meaning-of-exit-status-1-returned-by-linux-command#20966337)). 

I'm working on a script that does automation using plan/deploy, and these non-0 exit codes are tripping it up, even though nothing has technically gone wrong. 

Cheers

**Comment by rajaseelan** [comment]
Do you think this flag will help?
```
  -ignore-no-changes
    By default if no changes are detected when running a deployment Levant will
    exit with a status 1 to indicate a deployment didn't happen. This behaviour
    can be changed using this flag so that Levant will exit cleanly ensuring CD
    pipelines don't fail when no changes are detected.
```

**Comment by lhayhurst** [comment]
Missed that one! Thank you :-)
