### ISSUE TITLE
Latest release did not include prebuilt binaries

### ISSUE THREAD

**Issue by allancalix** [hashicorp/levant#432]
**Description**

The latest release (0.3.0) did not publish artifacts the way previous releases did.

**Relevant Nomad job specification file**

n/a

**Output of `levant version`:**
Levant v0.3.0-dev

**Output of `consul version`:**

n/a

**Output of `nomad version`:**

n/a

**Additional environment details:**
Following the installation instructions from the README does not work for the latest release. This may not be a supported way of installing the binary anymore, if so some clarification on the README would be helpful.

```sh
# Returns binary
curl -L https://github.com/hashicorp/levant/releases/download/0.2.9/linux-amd64-levant -o levant
```

```sh
# 404 - NOT FOUND
curl -L https://github.com/hashicorp/levant/releases/download/0.2.9/linux-amd64-levant -o levant
```

**Comment by tgross** [comment]
Hi @allancalix! The latest release 3.0.0 was made after the Levant project joined HashiCorp:

> The Levant binary can be downloaded from the GitHub releases page using curl -L https://github.com/hashicorp/levant/releases/download/0.2.9/linux-amd64-levant -o levant if you are using a release prior to the migration to the HashiCorp organisation. Releases after the migration can be found on the HashiCorp releases site.

You'll need to get 3.0.0 from https://releases.hashicorp.com/levant/0.3.0/.

That being said, having the "if you are..." language _after_ the `curl` command makes it awfully easy to miss. I'll open a PR to make the docs more clear.

**Comment by allancalix** [comment]
Got it, sorry I missed that! Thank you for clearing things up. Are there any plans to include `darwin-arm` builds for M1?

**Comment by tgross** [comment]
> Are there any plans to include `darwin-arm` builds for M1?

I'm sure we intend to do so, but I'm not sure that we have a timeline for that.
