### ISSUE TITLE
[OT Question] levant for etcd or alternatives?

### ISSUE THREAD

**Issue by gc-ss** [hashicorp/levant#449]
Apologies for this OT post but I have been looking around for an (open source) templating tool like levant, but that can read from other backends, like etcd and the only 2 I can find are:

- confd: deprecated but a fork at https://github.com/abtreece/confd
- remco: https://github.com/HeavyHorst/remco

I assumed the group/users here would be more informed about this need. Hence, this OT question.

1. Am I missing out on an awesome (open source) templating tool that can read from a distributed store like consul or etcd and can keep config files up to date?
2. Is there a possibility levant could become that tool one day?

**Comment by tgross** [comment]
Hi @gc-ss! I'm going to recommend you take this question to [Discuss](https://discuss.hashicorp.com/c/nomad/28), which might be a better fit for off-topic questions. Thanks!
