### ISSUE TITLE
Support latest Nomad 1.3.+ job descriptor

### ISSUE THREAD

**Issue by MartinAhrer** [hashicorp/levant#457]
**Description**

I'm trying the new Nomad service registry and replacing the consul provider by the nomad provider.
Deploying with `levant deploy` produces an error message complaining that the key `provider` is unknown.

**Relevant Nomad job specification file**

```
            service {
                name        = "continuousdelivery-api"
                provider    = "nomad"
                port        = "http"
            }
```

**Output of `levant version`:**

```
Levant v0.3.1
```

**Output of `consul version`:**

```
N/A
```

**Output of `nomad version`:**

```
Nomad v1.3.2
```

**Additional environment details:**

**Debug log outputs from Levant:**

```
[ERROR] levant/command: error parsing 'job': 1 error occurred:
	* group: 'api', task: 'api', service (0): invalid key: provider

```

**Comment by Fuco1** [comment]
Same problem with `max_client_disconnect`.  Can we get a new tag/release?  I see the dependency was already bumped to nomad 1.3.1 three months ago.
