### ISSUE TITLE
Levant is not up to date with nomad api version

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/levant#479]
Hello guys,

Levant version is not up to date with latest nomad api version.

When I'm trying to render a sidercar_service with a meta block from the documentation https://developer.hashicorp.com/nomad/docs/job-specification/sidecar_service I'm getting the error below:

```
Error getting job struct: Error parsing job file from render.nomad:
render.nomad:61,11-15: Unsupported block type; Blocks of type "meta" are not expected here.
```
It's normal because this block it's only supported in the 1.5.x version. You can have more informations [here](https://developer.hashicorp.com/nomad/docs/v1.4.x/job-specification/sidecar_service) and [here](https://github.com/hashicorp/levant/blob/v0.3.2/go.mod#L10)
 
**Output of `levant version`:**

```
v0.3.2
```

**Output of `consul version`:**

```
v1.15.2+ent
```

**Output of `nomad version`:**

```
v1.5.3
```

Can we have more release of levant compatible with the latest version of nomad?

Thx.

**Comment by jobartim44** [comment]
Is there any plan to release a new version of levant ?

**Comment by Lord-Y** [comment]
I stopped fighting @jobartim44
